# Audit Logging

# V-242463 - "The Kubernetes API Server must be set to audit log maximum backup."

# This policy checks if the kube-apiserver pod has the argument "--audit-log-maxbackup" set to a minimum of "10".
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kas-enforce-audit-maxbackup
  labels:
    group: kubernetes-security-policies
spec:
  validationFailureAction: Audit
  rules:
    - name: check-audit-maxbackup
      match:
        resources:
          kinds:
            - Pod
          names:
            - kube-apiserver-* # Name of Target Pod (can be changed for specific use case)
          namespaces:
            - kube-system # Target Namespace (can be changed for specific use case)
      validate:
        message: "The kube-apiserver must have --audit-log-maxbackup=10 "
        deny:
          conditions:
            all: 
              - key: "{{ request.object.spec.containers[].args[] }}"
                operator: AllNotIn
                value: ["--audit-log-maxbackup=10"]