# Audit Logging

# V-242462 - "The Kubernetes API Server must be set to audit log max size."

# This policy checks if the kube-apiserver pod has the argument "--audit-log-maxsize" set to a minimum of "100".
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kas-enforce-audit-max-size
  labels:
    group: kubernetes-security-policies
spec:
  validationFailureAction: Audit
  rules:
    - name: check-audit-max-size
      match:
        resources:
          kinds:
            - Pod
          names:
            - kube-apiserver-* # Name of Target Pod (can be changed for specific use case)
          namespaces:
            - kube-system # Target Namespace (can be changed for specific use case)
      validate:
        message: "The kube-apiserver must have --audit-log-maxsize=100"
        deny:
          conditions:
            all: 
              - key: "{{ request.object.spec.containers[].args[] }}"
                operator: AllNotIn
                value: ["--audit-log-maxsize=100"]