# Access Control - RBAC

# V-242385 - "The Kubernetes Controller Manager must have secure binding."

# This policy checks if the kube-controller-manager pod has the argument "--bind-address" set to "127.0.0.1".
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kcm-enforce-secure-binding
  labels:
    group: kubernetes-security-policies
spec:
  validationFailureAction: Audit
  rules:
    - name: check-secure-binding
      match:
        resources:
          kinds:
            - Pod
          names:
            - kube-controller-manager-* # Name of Target Pod (can be changed for specific use case)
          namespaces:
            - kube-system # Target Namespace (can be changed for specific use case)
      validate:
        message: "The kube-controller-manager must have --bind-address=127.0.0.1"
        deny:
          conditions:
            all: 
              - key: "{{ request.object.spec.containers[].args[] }}"
                operator: AllNotIn
                value: ["--bind-address=127.0.0.1"] 
