# Access Control - RBAC

# V-242381 - "The Kubernetes Controller Manager must create unique service accounts for each work payload."

# This policy checks if the kube-controller-manager pod has the argument "--unique-service-account-credentials" set to "true".
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kcm-enforce-service-account-credentials
  labels:
    group: kubernetes-security-policies
spec:
  validationFailureAction: Audit
  rules:
    - name: check-service-account-credentials 
      match:
        resources:
          kinds:
            - Pod
          names:
            - kube-controller-manager-* # Name of Target Pod (can be changed for specific use case)
          namespaces:
            - kube-system # Target Namespace (can be changed for specific use case)
      validate:
        message: "The kube-controller-manager must have --use-service-account-credentials=true"
        deny:
          conditions:
            all: 
              - key: "{{ request.object.spec.containers[].args[] }}"
                operator: AllNotIn
                value: ["--use-service-account-credentials=true"] 
