# Container/Pod Security

# V-242409 - "Kubernetes Controller Manager must disable profiling."

# This policy checks if the kube-controller-manager pod has the argument "--profiling value" set to "false".
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kcm-enforce-profiling
  labels:
    group: kubernetes-security-policies
spec:
  validationFailureAction: Audit
  rules:
    - name: check-profiling
      match:
        resources:
          kinds:
            - Pod
          names:
            - kube-controller-manager-* # Name of Target Pod (can be changed for specific use case)
          namespaces:
            - kube-system # Target Namespace (can be changed for specific use case)
      validate:
        message: "The kube-controller-manager must have --profiling value=false "
        deny:
          conditions:
            all: 
              - key: "{{ request.object.spec.containers[].args[] }}"
                operator: AllNotIn
                value: ["--profiling=false"]