# Network Policies

# V-242389 - "The Kubernetes API server must have the secure port set."

# This policy checks to make sure the kube-apiserver pod does NOT have the argument "--secure-port" set to "0"
# Policy violation occurs if --secure-port=0.
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kas-enforce-secure-port
  labels:
    group: kubernetes-security-policies
spec:
  validationFailureAction: Audit
  rules:
    - name: check-secure-port
      match:
        resources:
          kinds:
            - Pod
          names:
            - kube-apiserver-* # Name of Target Pod (can be changed for specific use case)
          namespaces:
            - kube-system # Target Namespace (can be changed for specific use case)
      validate:
        message: "The kube-apiserver must have --secure-port set to a value other than 0"
        deny:
          conditions:
            all: 
              - key: "{{ request.object.spec.containers[].args[] }}"
                operator: AnyIn # Deny pod creation if --secure-port=0 is present, --secure-port must be set to a value other than 0.
                value: ["--secure-port=0"]