apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    run: nginx
  namespace: default
spec:
  containers:
    - image: test
      name: test
      args:
        - "yeet=false"
        - "lit=true"
        - "foo=bar"
